vars:
  # dotfiles are used by both the install & stow freck, so we define them 'globally'. Could also define them as a 'run'-local variable though.
  dotfiles:
     - base_dir: ~/dotfiles-example
       remote: https://github.com/makkus/dotfiles-example.git
  # this holds apps where we don't have a dotfile folder, because the app does not have configuration files
  apps:
     - cowsay

runs:
  - name: checkout dotfiles
    frecks:
     - checkout
  - name: install packages, stow config
    frecks:
     - install:
         vars:
           no_install:
             - freckles
     - stow
 