- hosts: localhost

  vars:
    pkg_mgr: 'conda'
    install_action: 'install'
    conda_env: test
    conda_channels:
      - conda-forge
      - freckles
    pkgs:
      conda:
        - nano
        - stow
  roles:
    - install-pkg
