---
- name: update bew package cache
  become: no
  homebrew: update_homebrew=yes upgrade_all=no
  when: install_action == "update_cache"

- name: upgrade brew packages
  become: no
  homebrew: upgrade_all=yes update_homebrew=no
  when: install_action == "upgrade"

- name: install brew package
  become: no
  homebrew: name="{{ item }}" state="{{ pkg_state | default("present") }}"
  with_items:
    - "{{ pkgs['brew'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
