---
# install debian packages
- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "update_cache"

- name: upgrade deb packages
  become: yes
  apt:
    upgrade: dist
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "upgrade"

- name: install deb package
  become: yes
  apt:
    name: "{{ item }}"
    state: "{{ pkg_state | default('latest') }}"
    allow_unauthenticated: "{{ apt_allow_unauthenticated | default(omit) }}"
    autoremove: "{{ apt_autoremove | default(omit) }}"
    default_release: "{{ apt_default_release | default(omit) }}"
    dpkg_options: "{{ apt_dpkg_options | default(omit) }}"
    force: "{{ apt_force | default(omit) }}"
    install_recommends: "{{ apt_install_recommends | default(omit) }}"
    only_upgrade: "{{ apt_only_upgrade | default(omit) }}"
    purge: "{{ apt_purge | default(omit) }}"
  with_items:
    - "{{ pkgs['deb'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
