---
- name: install package from git
  become: no
  git:
    accept_hostkey: "{{ item.accept_hostkey | default(omit) }}"
    bare: "{{ item.bare | default(omit) }}"
    clone: "{{ item.clone | default(omit) }}"
    depth: "{{ item.depth | default(omit) }}"
    dest: "{{ item.dest }}"
    executable: "{{ item.executable | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
    key_file: "{{ item.key_file | default(omit) }}"
    recursive: "{{ item.recursive | default(omit) }}"
    reference: "{{ item.reference | default(omit) }}"
    refspec: "{{ item.refspec | default(omit) }}"
    remote: "{{ item.remote | default(omit) }}"
    repo: "{{ item.repo }}"
    ssh_opts: "{{ item.ssh_opts | default(omit) }}"
    track_submodules: "{{ item.track_submodules | default(omit) }}"
    umask: "{{ item.umask | default(omit)  }}"
    update: "{{ item.git_update | default(omit) }}"  # need to use git_update, becauase item.update apparently points to a dict object function
    verify_commit: "{{ item.verify_commit | default(omit) }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - "{{ pkgs['git'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
