---
- name: update nix package cache
  become: no
  nix: update_cache=yes
  when: install_action == "update_cache"

- name: upgrade nix packages
  become: no
  nix: upgrade=yes
  when: install_action == "upgrade"

- name: install nix package
  become: no
  nix: name="{{ item }}" state="{{ pkg_state | default("present") }}"
  with_items:
    - "{{ pkgs['nix'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
