---

- name: install pip package
  become: no
  pip:
    name: "{{ item }}"
    state: "{{ pkg_state | default(present) }}"
    chdir: "{{ pip_chdir | default(omit) }}"
    editable: "{{ pip_editable | default(omit) }}"
    executable: "{{ pip_executable | default(omit) }}"
    extra_args: "{{ pip_extra_args | default(omit) }}"
    requirements: "{{ pip_requirements | default(omit) }}"
    umask: "{{ pip_umask | default(omit) }}"
    version: "{{ pip_version | default(omit) }}"
    virtualenv: "{{ pip_virtualenv | default(omit) }}"
    virtualenv_command: "{{ pip_virtualenv_command | default(omit) }}"
    virtualenv_python: "{{ pip_virtualenv_python | default(omit) }}"
    virtualenv_site_packages: "{{ pip_virtualenv_site_packages | default(omit) }}"
  with_items:
    - "{{ pkgs['pip'] | default(pkgs['default']) }}"
  ignore_errors: "{{ ignore_errors | default('yes') }}"
  when: install_action == "install"
